apiVersion: apps/v1
kind: Deployment
metadata:
 name: rentfurlax-backend-deployment
spec:
 replicas: 3  
 selector:
   matchLabels:
     app: rentfurlax-backend
 template:
   metadata:
     labels:
       app: rentfurlax-backend
   spec:
     containers:
     - name: rentfurlax-backend-container
       image: ishantkr/rentfurlax-backend:latest
       ports:
       - containerPort: 8000
